require 'optparse'
require 'prime'
require_relative 'lib/sequence_template'

$stdout.sync = true # Ensure all terminal output is shown instantly
puts "OEIS Discovery Framework v#{OEIS::VERSION}"

# Dynamically load sequence keys from the flat sequences/ directory
def load_sequences
  print "[1/3] Scanning sequence directory... "
  sequences = {}
  Dir.glob(File.join(__dir__, 'sequences', '*.rb')).each do |file|
    key = File.basename(file, '.rb')
    sequences[key] = file
  end
  puts "Found #{sequences.size} sequences."
  sequences
end

# Helper to actually load a class from a file
def load_sequence_class(file)
  existing_classes = ObjectSpace.each_object(Class).select { |c| c < OEISSequence }.to_a
  require file
  new_classes = ObjectSpace.each_object(Class).select { |c| c < OEISSequence }
  (new_classes - existing_classes).first
end

def list_sequences(sequences)
  puts "[2/3] Loading sequence metadata for listing..."
  puts "%-30s | %-15s | %s" % ["Key", "Rank", "Name"]
  puts "-" * 80
  
  all_data = []
  sequences.each do |key, file|
    klass = load_sequence_class(file)
    instance = klass.new
    all_data << { key: key, rank: instance.rank, name: instance.name }
  end

  # Group by rank
  grouped = all_data.group_by { |d| d[:rank] }
  
  ["High Potential", "Medium Potential", "Experimental"].each do |rank|
    next unless grouped[rank]
    grouped[rank].each do |data|
      puts "%-30s | %-15s | %s" % [data[:key], rank, data[:name]]
    end
  end
  puts "[3/3] Done."
end

DOCUMENTER_VERSION = 1

def build_catalog(sequences)
  docs_dir = File.join(__dir__, 'docs', 'sequences')
  FileUtils.mkdir_p(docs_dir)
  FileUtils.mkdir_p('.cache')
  
  cache_path = '.cache/catalog.json'
  existing_catalog = File.exist?(cache_path) ? JSON.parse(File.read(cache_path)) : []
  catalog_map = existing_catalog.each_with_object({}) { |s, h| h[s['key']] = s }
  
  catalog_data = []
  
  # CRITICAL FIX: Load all classes once into a lookup table to avoid 'require' nil issues
  class_map = {}
  sequences.each do |key, file|
    class_map[key] = load_sequence_class(file)
  end

  # 1. Update Individual Sequence Docs
  class_map.each do |key, klass|
    next unless klass
    instance = klass.new
    doc_path = File.join(docs_dir, "#{key}.md")
    
    # Check current version in file
    existing_version = 0
    if File.exist?(doc_path)
      v_line = File.readlines(doc_path).find { |l| l.start_with?("Doc Version:") }
      existing_version = v_line.split(":").last.to_i if v_line
    end
    
    # Use cached score if available, otherwise analyze
    cached = catalog_map[key]
    if cached && existing_version >= DOCUMENTER_VERSION
      report = { fitness_score: cached['fitness_score'], stats: { terms: 1000 } }
      catalog_data << cached
    else
      puts "Analyzing #{key}..."
      report = instance.analyze(1000)
      catalog_data << {
        key: key,
        name: instance.name,
        rank: instance.rank,
        formula: instance.formula,
        fitness_score: report[:fitness_score]
      }
    end

    if existing_version < DOCUMENTER_VERSION
      puts "Updating documentation for #{key}..."
      
      File.open(doc_path, "w") do |f|
        f.puts "Doc Version: #{DOCUMENTER_VERSION}"
        f.puts "# #{instance.name}"
        f.puts "\n> **Formula:** `#{instance.formula}`"
        f.puts "\n## Description"
        f.puts instance.description
        
        f.puts "\n## OEIS Fitness Analysis"
        f.puts "Computed over #{report[:stats][:terms]} terms."
        f.puts "\n| Metric | Value |"
        f.puts "| :--- | :--- |"
        f.puts "| Final Score | **#{report[:fitness_score]} / 100** |"
        f.puts "| Growth Pattern | #{report[:stats][:growth_type]} |"
        f.puts "| Erraticness | #{report[:dynamics][:erraticness]} |"
        f.puts "| Significant Resets | #{report[:dynamics][:resets]} |"
        f.puts "| Prime Density | #{(report[:composition][:prime_density] * 100).round(2)}% |"
        f.puts "| Unique Ratio | #{(report[:composition][:unique_ratio] * 100).round(2)}% |"
        
        f.puts "\n## Sample Terms"
        f.puts "`#{instance.generate(50).join(', ')}`"
        
        f.puts "\n---"
        f.puts "*Generated by OEIS Discovery Framework Documenter v#{DOCUMENTER_VERSION}*"
      end
    end
  end

  # Save fast-loading JSON for GUI
  File.write('.cache/catalog.json', catalog_data.to_json)

  # 2. Update the Main CATALOG.md Index
  File.open("CATALOG.md", "w") do |f|
    f.puts "# OEIS Discovery Catalog"
    f.puts "\nThis catalog provides an index of all sequences implemented in this framework."
    
    ["High Potential", "Medium Potential", "Experimental"].each do |rank|
      f.puts "\n## #{rank} Sequences"
      f.puts "\n| Name | Formula | Doc |"
      f.puts "| :--- | :--- | :--- |"
      
      # Use class_map instead of reloading
      class_map.keys.sort.each do |key|
        klass = class_map[key]
        next unless klass
        instance = klass.new
        next unless instance.rank == rank
        f.puts "| #{instance.name} | `#{instance.formula}` | [View Full Report](docs/sequences/#{key}.md) |"
      end
    end
  end
  puts "CATALOG.md and individual docs have been updated."
end

sequences = load_sequences

options = {}
OptionParser.new do |opts|
  opts.banner = "OEIS Discovery Framework v#{OEIS::VERSION}\nUsage: ruby oeis_cli.rb [options] [command] [sequence_key] [count]"
  
  opts.on("-h", "--help", "Prints this help") do
    puts opts
    puts "\nCommands:"
    puts "  list              List all available sequences"
    puts "  generate <key> <n>  Print the first n terms of a sequence"
    puts "  analyze <key> <n>   Perform statistical analysis and fitness scoring"
    puts "  plot <key> <n>      Launch terminal plotter for first n terms"
    puts "  gui <key> <n>       Launch graphical explorer for first n terms"
    puts "  explore             Launch high-performance GPU visualizer"
    puts "  bfile <key> <n>     Generate a b-file in b_files/ directory"
    puts "  build-catalog     Auto-generate CATALOG.md"
    exit
  end
end.parse!

command = ARGV[0]
key = ARGV[1]
count = (ARGV[2] || 100).to_i

case command
when "list"
  list_sequences(sequences)
when "build-catalog"
  build_catalog(sequences)
when "explore"
  # Force immediate output
  STDOUT.sync = true

  puts "[1/4] Syncing metadata..."
  build_catalog(sequences)

  puts "[2/4] Initializing Dashboard..."
  dashboard_cmd = "bundle exec ruby lib/visualizers/gui_dashboard.rb"
  viewer_cmd = "bundle exec ruby lib/visualizers/raylib_viewer.rb"

  # On Windows, we need to be very careful with process management
  # We will use Threads to keep the console responsive
  threads = []

  puts "[3/4] Launching High-Performance Viewer..."
  puts "\n🚀 Discovery Station starting! Press Ctrl+C here to quit."

  pids = []
  begin
    # Use spawn to get PIDs for reliable cleanup
    pids << spawn(dashboard_cmd)
    pids << spawn(viewer_cmd)

    # Wait for the main viewer process
    Process.wait(pids.last)
  rescue Interrupt
    puts "\nExiting OEIS Discovery Station..."
  ensure
    pids.each do |pid|
      if RUBY_PLATFORM =~ /mswin|msys|mingw|cygwin/
        # /T kills the child processes (like bundle/ruby) as well
        system("taskkill /F /PID #{pid} /T >NUL 2>&1")
      else
        Process.kill("TERM", pid) rescue nil
      end
    end
  end
when "generate", "plot", "gui", "bfile", "analyze"
  unless sequences[key]
    puts "Error: Sequence '#{key}' not found. Use 'ruby oeis_cli.rb list' to see available keys."
    exit 1
  end
  
  case command
  when "analyze"
    klass = load_sequence_class(sequences[key])
    instance = klass.new
    puts "=========================================================="
    puts "      FULL OEIS FITNESS REPORT: #{instance.name}"
    puts "=========================================================="
    report = instance.analyze(count)
    
    puts "\n[ 1. BASIC STATISTICS ]"
    puts "Terms Generated:  #{report[:stats][:terms]}"
    puts "Value Range:      #{report[:stats][:min]} to #{report[:stats][:max]}"
    puts "Average Value:    #{report[:stats][:avg]}"
    puts "Growth Pattern:   #{report[:stats][:growth_type]}"
    puts "Is Periodic?      #{report[:stats][:is_periodic] ? 'YES (Warning: Low Fitness)' : 'No'}"
    
    puts "\n[ 2. DYNAMIC BEHAVIOR ]"
    puts "Average Swing:    #{report[:dynamics][:avg_swing]}"
    puts "Max Step Swing:   #{report[:dynamics][:max_swing]}"
    puts "Erraticness:      #{report[:dynamics][:erraticness]} (SD of swings)"
    puts "Significant Drops:#{report[:dynamics][:resets]} (>50% reset)"
    
    puts "\n[ 3. COMPOSITION ]"
    puts "Prime Density:    #{(report[:composition][:prime_density] * 100).round(2)}%"
    puts "Zero Density:     #{(report[:composition][:zero_density] * 100).round(2)}%"
    puts "Uniqueness Ratio: #{(report[:composition][:unique_ratio] * 100).round(2)}%"
    
    puts "\n[ 4. SCORING BREAKDOWN ]"
    puts "Diversity Score:  #{report[:scoring][:diversity].round(1)} / 25"
    puts "Activity Score:   #{report[:scoring][:activity].round(1)} / 25"
    puts "Novelty Score:    #{report[:scoring][:novelty].round(1)} / 25"
    puts "Longevity Score:  #{report[:scoring][:longevity].round(1)} / 25"
    
    puts "\n----------------------------------------------------------"
    printf("FINAL FITNESS SCORE: %.1f / 100\n", report[:fitness_score])
    puts "----------------------------------------------------------"
    
    case report[:fitness_score]
    when 0..30 then puts "STATUS: POOR - High probability of being trivial or periodic."
    when 31..60 then puts "STATUS: FAIR - Interesting behavior, but may lack enough 'surprise'."
    when 61..85 then puts "STATUS: STRONG - Highly recommended for OEIS search/submission."
    else puts "STATUS: ELITE - Exceptional mathematical profile. Submit ASAP."
    end
    puts "=========================================================="
  when "generate"
    klass = load_sequence_class(sequences[key])
    instance = klass.new
    puts "Generating #{count} terms for #{instance.name}..."
    puts instance.generate(count).join(", ")
  when "plot"
    require_relative 'lib/visualizers/oeis_plotter'
    klass = load_sequence_class(sequences[key])
    instance = klass.new
    terms = instance.generate(count)
    OEISPlotter.plot(terms)
  when "gui"
    # The new GUI has a combobox, so the key is optional
    system "bundle exec ruby lib/visualizers/oeis_gui.rb"
  when "bfile"
    klass = load_sequence_class(sequences[key])
    instance = klass.new
    puts "Generating b-file for #{instance.name} (up to a(#{count-1}))..."
    terms = instance.generate(count)
    path = File.join(__dir__, 'b_files', "b_#{key}.txt")
    File.open(path, "w") do |f|
      terms.each_with_index { |v, i| f.puts "#{i} #{v}" }
    end
    puts "Saved to #{path}"
  end
else
  puts "Unknown command. Use --help for usage."
end
