require 'optparse'
require 'prime'
require 'json'
require 'fileutils'
require_relative 'lib/sequence_template'

$stdout.sync = true # Ensure all terminal output is shown instantly
puts "OEIS Discovery Framework v#{OEIS::VERSION}"

# Dynamically load sequence keys from the flat sequences/ directory
def load_sequences
  print "[1/3] Scanning sequence directory... "
  sequences = {}
  Dir.glob(File.join(__dir__, 'sequences', '*.rb')).each do |file|
    key = File.basename(file, '.rb')
    sequences[key] = file
  end
  puts "Found #{sequences.size} sequences."
  sequences
end

# Helper to actually load a class from a file
def load_sequence_class(file)
  existing_classes = ObjectSpace.each_object(Class).select { |c| c < OEISSequence }.to_a
  require file
  new_classes = ObjectSpace.each_object(Class).select { |c| c < OEISSequence }
  (new_classes - existing_classes).first
end

def list_sequences(sequences)
  puts "[2/3] Loading sequence metadata for listing..."
  puts "%-30s | %-15s | %s" % ["Key", "Rank", "Name"]
  puts "-" * 80
  
  all_data = []
  sequences.each do |key, file|
    klass = load_sequence_class(file)
    if klass
      instance = klass.new
      all_data << { key: key, rank: instance.rank, name: instance.name }
    end
  end

  # Group by rank
  grouped = all_data.group_by { |d| d[:rank] }
  
  ["High Potential", "Medium Potential", "Experimental"].each do |rank|
    next unless grouped[rank]
    grouped[rank].each do |data|
      puts "%-30s | %-15s | %s" % [data[:key], rank, data[:name]]
    end
  end
  puts "[3/3] Done."
end

DOCUMENTER_VERSION = 1

def build_catalog(sequences, force: false)
  cache_path = '.cache/catalog.json'
  docs_dir = File.join(__dir__, 'docs', 'sequences')
  
  # Check if we can skip the heavy scan
  if !force && File.exist?(cache_path)
    cache_time = File.mtime(cache_path)
    needs_update = sequences.values.any? { |f| File.mtime(f) > cache_time }
    return unless needs_update
    puts "[1/4] Detecting changes in sequences... Re-syncing cache."
  end

  FileUtils.mkdir_p(docs_dir)
  FileUtils.mkdir_p('.cache')
  
  existing_catalog = File.exist?(cache_path) ? (JSON.parse(File.read(cache_path)) rescue []) : []
  catalog_map = existing_catalog.each_with_object({}) { |s, h| h[s['key']] = s }
  
  catalog_data = []
  class_map = {}

  sequences.each do |key, file|
    klass = load_sequence_class(file)
    next unless klass
    class_map[key] = klass
    instance = klass.new
    doc_path = File.join(docs_dir, "#{key}.md")
    
    existing_version = 0
    if File.exist?(doc_path)
      v_line = File.readlines(doc_path).find { |l| l.start_with?("Doc Version:") }
      existing_version = v_line.split(":").last.to_i if v_line
    end
    
    cached = catalog_map[key]
    if cached && File.mtime(file) < File.mtime(cache_path) && existing_version >= DOCUMENTER_VERSION
      catalog_data << cached
    else
      puts "Analyzing #{key}..."
      report = instance.analyze(1000)
      catalog_data << {
        key: key,
        name: instance.name,
        rank: instance.rank,
        formula: instance.formula,
        fitness_score: report[:fitness_score]
      }
    end

    if existing_version < DOCUMENTER_VERSION
      puts "Updating documentation for #{key}..."
      report ||= instance.analyze(1000)
      File.open(doc_path, "w") do |f|
        f.puts "Doc Version: #{DOCUMENTER_VERSION}"
        f.puts "# #{instance.name}"
        f.puts "\n> **Formula:** `#{instance.formula}`"
        f.puts "\n## Description"
        f.puts instance.description
        f.puts "\n## OEIS Fitness Analysis"
        f.puts "Computed over 1000 terms."
        f.puts "\n| Metric | Value |"
        f.puts "| :--- | :--- |"
        f.puts "| Final Score | **#{report[:fitness_score]} / 100** |"
        f.puts "| Growth Pattern | #{report[:stats][:growth_type]} |"
        f.puts "| Erraticness | #{report[:dynamics][:erraticness]} |"
        f.puts "| Significant Resets | #{report[:dynamics][:resets]} |"
        f.puts "| Prime Density | #{(report[:composition][:prime_density] * 100).round(2)}% |"
        f.puts "| Unique Ratio | #{(report[:composition][:unique_ratio] * 100).round(2)}% |"
        f.puts "\n## Sample Terms"
        f.puts "`#{instance.generate(50).join(', ')}`"
        f.puts "\n---"
        f.puts "*Generated by OEIS Discovery Framework Documenter v#{DOCUMENTER_VERSION}*"
      end
    end
  end

  File.write(cache_path, catalog_data.to_json)

  File.open("CATALOG.md", "w") do |f|
    f.puts "# OEIS Discovery Catalog"
    f.puts "\nThis catalog provides an index of all sequences implemented in this framework."
    ["High Potential", "Medium Potential", "Experimental"].each do |rank|
      f.puts "\n## #{rank} Sequences"
      f.puts "\n| Name | Formula | Doc |"
      f.puts "| :--- | :--- | :--- |"
      catalog_data.select { |s| s['rank'] == rank || s[:rank] == rank }
                  .sort_by { |s| -(s['fitness_score'] || s[:fitness_score]) }
                  .each do |s|
        f.puts "| #{s['name'] || s[:name]} | `#{s['formula'] || s[:formula]}` | [View Full Report](docs/sequences/#{s['key'] || s[:key]}.md) |"
      end
    end
  end
  puts "CATALOG.md and individual docs have been updated."
end

sequences = load_sequences

OptionParser.new do |opts|
  opts.banner = "OEIS Discovery Framework v#{OEIS::VERSION}\nUsage: ruby oeis_cli.rb [options] [command] [sequence_key] [count]"
  opts.on("-h", "--help", "Prints this help") do
    puts opts
    puts "\nCommands:"
    puts "  list              List all available sequences"
    puts "  generate <key> <n>  Print the first n terms of a sequence"
    puts "  analyze <key> <n>   Perform statistical analysis and fitness scoring"
    puts "  plot <key> <n>      Launch terminal plotter for first n terms"
    puts "  gui               Launch graphical dashboard explorer"
    puts "  explore           Launch high-performance GPU visualizer"
    puts "  bfile <key> <n>     Generate a b-file in b_files/ directory"
    puts "  build-catalog     Force rebuild of CATALOG.md and docs"
    exit
  end
end.parse!

command = ARGV[0]
key = ARGV[1]
count = (ARGV[2] || 100).to_i

case command
when "list"
  list_sequences(sequences)
when "build-catalog"
  build_catalog(sequences, force: true)
when "explore"
  puts "[1/4] Checking metadata cache..."
  build_catalog(sequences)
  dashboard_cmd = "bundle exec ruby lib/visualizers/gui_dashboard.rb"
  viewer_cmd = "bundle exec ruby lib/visualizers/raylib_viewer.rb"
  puts "[2/4] Initializing Dashboard..."
  puts "[3/4] Launching Viewer..."
  puts "\n🚀 Discovery Station starting! Press Ctrl+C here to quit."
  pids = []
  begin
    # Use explicit IO redirection to ensure output is visible in the console
    pids << spawn(dashboard_cmd, out: :out, err: :err)
    pids << spawn(viewer_cmd, out: :out, err: :err)
    
    # Wait for BOTH processes in separate threads
    t1 = Thread.new { Process.wait(pids[0]) rescue nil }
    t2 = Thread.new { Process.wait(pids[1]) rescue nil }
    
    # Block the main thread until either sub-process exits
    loop do
      break unless t1.alive? && t2.alive?
      sleep 0.1
    end
    
  rescue Interrupt
    puts "\nInterrupt received. Cleaning up..."
  ensure
    pids.each do |pid|
      if RUBY_PLATFORM =~ /mswin|msys|mingw|cygwin/
        system("taskkill /F /PID #{pid} /T >NUL 2>&1")
      else
        Process.kill("TERM", pid) rescue nil
      end
    end
    puts "OEIS Discovery Station shutdown complete."
  end
when "analyze"
  if sequences[key]
    klass = load_sequence_class(sequences[key])
    instance = klass.new
    report = instance.analyze(count)
    puts "=========================================================="
    puts "      FULL OEIS FITNESS REPORT: #{instance.name}"
    puts "=========================================================="
    puts "\n[ 1. BASIC STATISTICS ]"
    puts "Terms Generated:  #{report[:stats][:terms]}"
    puts "Value Range:      #{report[:stats][:min]} to #{report[:stats][:max]}"
    puts "Average Value:    #{report[:stats][:avg]}"
    puts "Growth Pattern:   #{report[:stats][:growth_type]}"
    puts "\n[ 2. DYNAMIC BEHAVIOR ]"
    puts "Average Swing:    #{report[:dynamics][:avg_swing]}"
    puts "Max Step Swing:   #{report[:dynamics][:max_swing]}"
    puts "Erraticness:      #{report[:dynamics][:erraticness]}"
    puts "Significant Drops:#{report[:dynamics][:resets]}"
    puts "\n[ 3. COMPOSITION ]"
    puts "Prime Density:    #{(report[:composition][:prime_density] * 100).round(2)}%"
    puts "Unique Ratio:     #{(report[:composition][:unique_ratio] * 100).round(2)}%"
    puts "\n[ 4. SCORING ]"
    printf("FINAL FITNESS SCORE: %.1f / 100\n", report[:fitness_score])
    puts "=========================================================="
  else
    puts "Error: Sequence '#{key}' not found."
  end
when "generate"
  if sequences[key]
    klass = load_sequence_class(sequences[key])
    puts klass.new.generate(count).join(", ")
  end
when "plot"
  if sequences[key]
    require_relative 'lib/visualizers/oeis_plotter'
    klass = load_sequence_class(sequences[key])
    OEISPlotter.plot(klass.new.generate(count))
  end
when "bfile"
  if sequences[key]
    klass = load_sequence_class(sequences[key])
    instance = klass.new
    terms = instance.generate(count)
    path = File.join(__dir__, 'b_files', "b_#{key}.txt")
    File.open(path, "w") { |f| terms.each_with_index { |v, i| f.puts "#{i} #{v}" } }
    puts "Saved to #{path}"
  end
else
  puts "Unknown command. Use --help for usage."
end
