require 'optparse'
require 'prime'
require_relative 'lib/sequence_template'

# Dynamically load all sequences from the sequences/ directory
def load_sequences
  sequences = {}
  # Use a temporary set to keep track of already loaded classes to avoid duplicates
  existing_classes = ObjectSpace.each_object(Class).select { |c| c < OEISSequence }.to_a

  Dir.glob(File.join(__dir__, 'sequences', '**', '*.rb')).each do |file|
    require_relative file
    
    # After requiring, find the NEW class added to the system
    new_classes = ObjectSpace.each_object(Class).select { |c| c < OEISSequence }
    klass = (new_classes - existing_classes).first
    
    if klass
      key = File.basename(file, '.rb')
      sequences[key] = klass
      existing_classes << klass
    end
  end
  sequences
end

def list_sequences(sequences)
  puts "%-30s | %-15s | %s" % ["Key", "Rank", "Name"]
  puts "-" * 80
  
  # Group by rank
  grouped = sequences.values.group_by { |k| k.new.rank }
  
  ["High Potential", "Medium Potential", "Experimental"].each do |rank|
    next unless grouped[rank]
    grouped[rank].each do |klass|
      instance = klass.new
      key = sequences.key(klass)
      puts "%-30s | %-15s | %s" % [key, rank, instance.name]
    end
  end
end

DOCUMENTER_VERSION = 1

def build_catalog(sequences)
  docs_dir = File.join(__dir__, 'docs', 'sequences')
  FileUtils.mkdir_p(docs_dir)
  FileUtils.mkdir_p('.cache')
  
  cache_path = '.cache/catalog.json'
  existing_catalog = File.exist?(cache_path) ? JSON.parse(File.read(cache_path)) : []
  catalog_map = existing_catalog.each_with_object({}) { |s, h| h[s['key']] = s }
  
  catalog_data = []

  # 1. Update Individual Sequence Docs
  sequences.each do |key, klass|
    instance = klass.new
    doc_path = File.join(docs_dir, "#{key}.md")
    
    # Check current version in file
    existing_version = 0
    if File.exist?(doc_path)
      v_line = File.readlines(doc_path).find { |l| l.start_with?("Doc Version:") }
      existing_version = v_line.split(":").last.to_i if v_line
    end
    
    # Use cached score if available, otherwise analyze
    cached = catalog_map[key]
    if cached && existing_version >= DOCUMENTER_VERSION
      report = { fitness_score: cached['fitness_score'], stats: { terms: 1000 } } # dummy report for doc
      catalog_data << cached
    else
      puts "Analyzing #{key}..."
      report = instance.analyze(1000)
      catalog_data << {
        key: key,
        name: instance.name,
        rank: instance.rank,
        formula: instance.formula,
        fitness_score: report[:fitness_score]
      }
    end

    if existing_version < DOCUMENTER_VERSION
      puts "Updating documentation for #{key}..."
      # ... (rest of doc generation code)
      
      File.open(doc_path, "w") do |f|
        f.puts "Doc Version: #{DOCUMENTER_VERSION}"
        f.puts "# #{instance.name}"
        f.puts "\n> **Formula:** `#{instance.formula}`"
        f.puts "\n## Description"
        f.puts instance.description
        
        f.puts "\n## OEIS Fitness Analysis"
        f.puts "Computed over #{report[:stats][:terms]} terms."
        f.puts "\n| Metric | Value |"
        f.puts "| :--- | :--- |"
        f.puts "| Final Score | **#{report[:fitness_score]} / 100** |"
        f.puts "| Growth Pattern | #{report[:stats][:growth_type]} |"
        f.puts "| Erraticness | #{report[:dynamics][:erraticness]} |"
        f.puts "| Significant Resets | #{report[:dynamics][:resets]} |"
        f.puts "| Prime Density | #{(report[:composition][:prime_density] * 100).round(2)}% |"
        f.puts "| Unique Ratio | #{(report[:composition][:unique_ratio] * 100).round(2)}% |"
        
        f.puts "\n## Sample Terms"
        f.puts "`#{instance.generate(50).join(', ')}`"
        
        f.puts "\n---"
        f.puts "*Generated by OEIS Discovery Framework Documenter v#{DOCUMENTER_VERSION}*"
      end
    end
  end

  # Save fast-loading JSON for GUI
  File.write('.cache/catalog.json', catalog_data.to_json)

  # 2. Update the Main CATALOG.md Index
  File.open("CATALOG.md", "w") do |f|
    f.puts "# OEIS Discovery Catalog"
    f.puts "\nThis catalog is auto-generated and provides an index of all sequences implemented in this framework."
    
    ["High Potential", "Medium Potential", "Experimental"].each do |rank|
      f.puts "\n## #{rank} Sequences"
      f.puts "\n| Name | Formula | Doc |"
      f.puts "| :--- | :--- | :--- |"
      
      sequences.sort.each do |key, klass|
        instance = klass.new
        next unless instance.rank == rank
        f.puts "| #{instance.name} | `#{instance.formula}` | [View Full Report](docs/sequences/#{key}.md) |"
      end
    end
  end
  puts "CATALOG.md and individual docs have been updated."
end

sequences = load_sequences

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: ruby oeis_cli.rb [options] [command] [sequence_key] [count]"
  
  opts.on("-h", "--help", "Prints this help") do
    puts opts
    puts "\nCommands:"
    puts "  list              List all available sequences"
    puts "  generate <key> <n>  Print the first n terms of a sequence"
    puts "  analyze <key> <n>   Perform statistical analysis and fitness scoring"
    puts "  plot <key> <n>      Launch terminal plotter for first n terms"
    puts "  gui <key> <n>       Launch graphical explorer for first n terms"
    puts "  explore             Launch high-performance GPU visualizer"
    puts "  bfile <key> <n>     Generate a b-file in b_files/ directory"
    puts "  build-catalog     Auto-generate CATALOG.md"
    exit
  end
end.parse!

command = ARGV[0]
key = ARGV[1]
count = (ARGV[2] || 100).to_i

case command
when "list"
  list_sequences(sequences)
when "build-catalog"
  build_catalog(sequences)
when "explore"
  # 1. Build catalog first to ensure cache exists
  build_catalog(sequences)
  
  dashboard_cmd = "bundle exec ruby lib/visualizers/gui_dashboard.rb"
  viewer_cmd = "bundle exec ruby lib/visualizers/raylib_viewer.rb"
  
  puts "Launching OEIS Discovery Station..."
  puts "Press Ctrl+C in this console to exit both windows."
  
  pids = []
  begin
    if RUBY_PLATFORM =~ /mswin|msys|mingw|cygwin/
      pids << spawn(dashboard_cmd)
      pids << spawn(viewer_cmd)
    else
      pids << spawn(dashboard_cmd)
      pids << spawn(viewer_cmd)
    end
    
    # Wait for the processes to finish
    pids.each { |pid| Process.wait(pid) rescue nil }
  rescue Interrupt
    puts "\nExiting OEIS Discovery Station..."
  ensure
    pids.each do |pid|
      if RUBY_PLATFORM =~ /mswin|msys|mingw|cygwin/
        system("taskkill /F /PID #{pid} >NUL 2>&1")
      else
        Process.kill("TERM", pid) rescue nil
      end
    end
  end
when "generate", "plot", "gui", "bfile", "analyze"
  unless sequences[key]
    puts "Error: Sequence '#{key}' not found. Use 'ruby oeis_cli.rb list' to see available keys."
    exit 1
  end
  
  instance = sequences[key].new
  
  case command
  when "analyze"
    puts "=========================================================="
    puts "      FULL OEIS FITNESS REPORT: #{instance.name}"
    puts "=========================================================="
    report = instance.analyze(count)
    
    puts "\n[ 1. BASIC STATISTICS ]"
    puts "Terms Generated:  #{report[:stats][:terms]}"
    puts "Value Range:      #{report[:stats][:min]} to #{report[:stats][:max]}"
    puts "Average Value:    #{report[:stats][:avg]}"
    puts "Growth Pattern:   #{report[:stats][:growth_type]}"
    puts "Is Periodic?      #{report[:stats][:is_periodic] ? 'YES (Warning: Low Fitness)' : 'No'}"
    
    puts "\n[ 2. DYNAMIC BEHAVIOR ]"
    puts "Average Swing:    #{report[:dynamics][:avg_swing]}"
    puts "Max Step Swing:   #{report[:dynamics][:max_swing]}"
    puts "Erraticness:      #{report[:dynamics][:erraticness]} (SD of swings)"
    puts "Significant Drops:#{report[:dynamics][:resets]} (>50% reset)"
    
    puts "\n[ 3. COMPOSITION ]"
    puts "Prime Density:    #{(report[:composition][:prime_density] * 100).round(2)}%"
    puts "Zero Density:     #{(report[:composition][:zero_density] * 100).round(2)}%"
    puts "Uniqueness Ratio: #{(report[:composition][:unique_ratio] * 100).round(2)}%"
    
    puts "\n[ 4. SCORING BREAKDOWN ]"
    puts "Diversity Score:  #{report[:scoring][:diversity].round(1)} / 25"
    puts "Activity Score:   #{report[:scoring][:activity].round(1)} / 25"
    puts "Novelty Score:    #{report[:scoring][:novelty].round(1)} / 25"
    puts "Longevity Score:  #{report[:scoring][:longevity].round(1)} / 25"
    
    puts "\n----------------------------------------------------------"
    printf("FINAL FITNESS SCORE: %.1f / 100\n", report[:fitness_score])
    puts "----------------------------------------------------------"
    
    case report[:fitness_score]
    when 0..30 then puts "STATUS: POOR - High probability of being trivial or periodic."
    when 31..60 then puts "STATUS: FAIR - Interesting behavior, but may lack enough 'surprise'."
    when 61..85 then puts "STATUS: STRONG - Highly recommended for OEIS search/submission."
    else puts "STATUS: ELITE - Exceptional mathematical profile. Submit ASAP."
    end
    puts "=========================================================="
  when "generate"
    puts "Generating #{count} terms for #{instance.name}..."
    puts instance.generate(count).join(", ")
  when "plot"
    require_relative 'lib/visualizers/oeis_plotter'
    terms = instance.generate(count)
    OEISPlotter.plot(terms)
  when "gui"
    # The new GUI has a combobox, so the key is optional
    system "bundle exec ruby lib/visualizers/oeis_gui.rb"
  when "bfile"
    puts "Generating b-file for #{instance.name} (up to a(#{count-1}))..."
    terms = instance.generate(count)
    path = File.join(__dir__, 'b_files', "b_#{key}.txt")
    File.open(path, "w") do |f|
      terms.each_with_index { |v, i| f.puts "#{i} #{v}" }
    end
    puts "Saved to #{path}"
  end
else
  puts "Unknown command. Use --help for usage."
end
